// Generated by  grogu  starting from JINJA templated  offset_defines.vh  file

`ifndef __REGPOOL_VH__
`define __REGPOOL_VH__

`define WEIGHT_0_OFFSET 2'h0
`define WEIGHT_1_OFFSET 2'h1
`define BIAS_OFFSET 2'h2
`define RESULT_OFFSET 2'h3

`endif /* __REGPOOL_VH__ */