// Generated by  grogu  starting from JINJA templated  offset_defines.vh  file

`ifndef __REGPOOL_VH__
`define __REGPOOL_VH__

`define WEIGHT_0_OFFSET 4'h0
`define WEIGHT_1_OFFSET 4'h1
`define BIAS_OFFSET 4'h2
`define VALUE_IN_OFFSET 4'h3
`define CTRL_OFFSET 4'h4
`define STATUS_OFFSET 4'h5
`define RESULT_OFFSET 4'h6
`define MULT_RESULT_OFFSET 4'h7
`define ADD_RESULT_OFFSET 4'h8
`define BIAS_ADD_RESULT_OFFSET 4'h9

`endif /* __REGPOOL_VH__ */